# Docker Compose to run app + PostgreSQL
version: '2.4'

services:
  db:
    image: postgres:15
    container_name: postgres-01
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  test-db:
    image: postgres:15
    container_name: testdb
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"

  web:
    build: .
    container_name: fastapi-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${APP_PORT}:8000"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
    volumes:
      - .:/app

volumes:
  postgres_data: