"""Initial migrationa t

Revision ID: 2a3740263f43
Revises: 5d9e9ca41d8d
Create Date: 2025-06-04 10:06:46.458270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3740263f43'
down_revision: Union[str, None] = '5d9e9ca41d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('message_recipients_message_id_fkey'), 'message_recipients', type_='foreignkey')
    op.drop_constraint(op.f('message_recipients_recipient_id_fkey'), 'message_recipients', type_='foreignkey')
    op.create_foreign_key(None, 'message_recipients', 'users', ['recipient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'message_recipients', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'])
    op.drop_constraint(None, 'message_recipients', type_='foreignkey')
    op.drop_constraint(None, 'message_recipients', type_='foreignkey')
    op.create_foreign_key(op.f('message_recipients_recipient_id_fkey'), 'message_recipients', 'users', ['recipient_id'], ['id'])
    op.create_foreign_key(op.f('message_recipients_message_id_fkey'), 'message_recipients', 'messages', ['message_id'], ['id'])
    # ### end Alembic commands ###
